
services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erie_app
    restart: unless-stopped
    networks:
      - erie_network
    expose:
      - "8000"
    volumes:
      - ./api/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:stable
    container_name: erie_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/custom/mime.types:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - erie_network
    depends_on:
      - model

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: erie_fail2ban
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban/data:/data
      - ./fail2ban/config:/etc/fail2ban/filter.d:ro
      - ./fail2ban/config:/etc/fail2ban/jail.d:ro
      - ./nginx/logs:/var/log/nginx:ro
    environment:
      - TZ=America/Toronto
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=30d

networks:
  erie_network:
    driver: bridge